package service;

import dao.AccountDao;
import dao.CustomerDao;
import dao.TransactionDao;
import model.Account;
import model.Customer;

import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Scanner;

public class BankService {
    private  static AccountDao accountDao = new AccountDao();
    private static CustomerDao customerDao = new CustomerDao();
    private static TransactionDao transactionDao = new TransactionDao();


    public void createAccount(String fname, String lname, String email, String phoneNumber, String address, long adharNumber, String panNumber) {
        //first, you have to create a customer object.
        Customer customer = new Customer(adharNumber,panNumber,address,phoneNumber,email,lname,fname);

        //than, get the customer id generated by the DBMS and use it to create a bank account in dbms.

        //than, you have to insert the details of this particlular customer into the DBMS.
        try{
         int customerId =   customerDao.createCustomer(customer);
         if(customerId == -1){
             System.out.println("Failed to create customer db");
             return;
         }

         long accNumber = (long) Math.random() * 10000000000000l;

            Account account = new Account(accNumber, customerId, "Saving", 0.0d, "Active", LocalDate.now());

         accountDao.createBankAccount(account);



        } catch (SQLException e) {
            System.out.println("Erro : " +e.getMessage());
        }


    }
}
